"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                {/* <!-- Essential Meta Tags --> */}
                <meta charSet="UTF-8" />
                <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />

                {/* <!-- SEO Title and Description --> */}
                <title>Best SEO Practices for 2024 | Ultimate Guide</title>
                <meta
                    name="description"
                    content="Learn the best SEO practices for 2024 to rank higher on Google and increase your website's traffic. Comprehensive guide covering on-page and off-page SEO."
                />

                {/* <!-- Keywords (Some Search Engines Use It) --> */}
                <meta
                    name="keywords"
                    content="SEO 2024, SEO best practices, Google ranking, on-page SEO, off-page SEO, SEO guide, SEO techniques, search engine optimization, technical SEO, content SEO"
                />

                {/* <!-- Canonical URL --> */}
                <link
                    rel="canonical"
                    href="https://www.example.com/best-seo-practices-2024"
                />

                {/* <!-- Open Graph Meta Tags --> */}
                <meta property="og:type" content="website" />
                <meta
                    property="og:title"
                    content="Best SEO Practices for 2024 | Ultimate Guide"
                />
                <meta
                    property="og:description"
                    content="Discover top SEO strategies for 2024 to improve your search engine rankings and drive more organic traffic to your site."
                />
                <meta
                    property="og:url"
                    content="https://www.example.com/best-seo-practices-2024"
                />
                <meta
                    property="og:image"
                    content="https://www.example.com/images/seo-guide-2024.jpg"
                />
                <meta property="og:image:alt" content="SEO Guide Cover Image" />
                <meta property="og:site_name" content="SEO Experts Hub" />

                {/* <!-- Twitter Card Meta Tags --> */}
                <meta name="twitter:card" content="summary_large_image" />
                <meta
                    name="twitter:title"
                    content="Best SEO Practices for 2024 | Ultimate Guide"
                />
                <meta
                    name="twitter:description"
                    content="Learn top SEO strategies to boost your rankings in 2024. Expert guide to on-page, off-page, and technical SEO."
                />
                <meta
                    name="twitter:image"
                    content="https://www.example.com/images/seo-guide-2024.jpg"
                />
                <meta name="twitter:site" content="@SEOExpertsHub" />
                <meta name="twitter:creator" content="@AuthorHandle" />

                {/* <!-- Schema.org (Structured Data) --> */}
                <script
                    type="application/ld+json"
                    dangerouslySetInnerHTML={{
                        __html: JSON.stringify({
                            "@context": "https://schema.org",
                            "@type": "Article",
                            mainEntityOfPage: {
                                "@type": "WebPage",
                                "@id": "https://www.example.com/best-seo-practices-2024",
                            },
                            headline:
                                "Best SEO Practices for 2024 | Ultimate Guide",
                            description:
                                "Learn top SEO strategies to improve rankings in 2024. A comprehensive guide covering all aspects of SEO including on-page, off-page, and technical SEO.",
                            image: "https://www.example.com/images/seo-guide-2024.jpg",
                            author: {
                                "@type": "Person",
                                name: "John Doe",
                            },
                            publisher: {
                                "@type": "Organization",
                                name: "SEO Experts Hub",
                                logo: {
                                    "@type": "ImageObject",
                                    url: "https://www.example.com/images/logo.png",
                                },
                            },
                            datePublished: "2024-01-15",
                            dateModified: "2024-01-15",
                        }),
                    }}
                />

                {/* <!-- Favicon --> */}
                <link
                    rel="icon"
                    href="https://www.example.com/favicon.ico"
                    type="image/x-icon"
                />

                {/* <!-- Robots Meta Tag --> */}
                <meta name="robots" content="index, follow" />

                {/* <!-- Author Meta Tag --> */}
                <meta name="author" content="John Doe" />

                {/* <!-- Referrer Meta Tag --> */}
                <meta name="referrer" content="no-referrer-when-downgrade" />

                {/* <!-- Theme Color --> */}
                <meta name="theme-color" content="#ffffff" />

                {/* <!-- Apple Touch Icon --> */}
                <link
                    rel="apple-touch-icon"
                    href="https://www.example.com/images/apple-touch-icon.png"
                />

                {/* <!-- RSS Feed (Optional) --> */}
                <link
                    rel="alternate"
                    type="application/rss+xml"
                    title="RSS Feed"
                    href="https://www.example.com/rss-feed.xml"
                />
            </Head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
